### ISSUE TITLE
Adding a screen shot to the submission

### ISSUE THREAD

**Issue by snarshad** [zendesk/zendesk_ios_sdk#3]
Hi, I attempted to post a screenshot along with the ticket - you can see my code at:

https://github.com/snarshad/zendesk_ios_sdk

It submits OK, but I was hoping the screenshot would be magically attached when I viewed the ticket on Zendesk.  Any ideas on getting this to work?

**Comment by maximeprades** [comment]
Hey @snarshad this repository is being deprecated in favor of this one: 

https://github.com/zendesk/zendesk_sdk_ios

Additionally you can find detailed technical documentation here: 

https://developer.zendesk.com/embeddables/docs/ios/overview

And finally reference customers here:

https://www.zendesk.com/embeddables
