### ISSUE TITLE
Way to set custom ticket fields 

### ISSUE THREAD

**Issue by natanrolnik** [zendesk/zendesk_ios_sdk#6]
The documentation is not clear if I can set custom ticket fields for a ticket. Is it possible with the current version of Zendesk iOS SDK?

**Comment by maximeprades** [comment]
Hey @natanrolnik this repository is being deprecated in favor of this one: 

https://github.com/zendesk/zendesk_sdk_ios

Additionally you can find detailed technical documentation here: 

https://developer.zendesk.com/embeddables/docs/ios/overview

And finally reference customers here:

https://www.zendesk.com/embeddables
