### ISSUE TITLE
Arm64 support?

### ISSUE THREAD

**Issue by overlordnyaldee** [zendesk/zendesk_ios_sdk#8]
Library does not seem to support Arm64, and the latest versions of Xcode are starting to include it as default.

**Comment by metalmalte** [comment]
+1

**Comment by maximeprades** [comment]
Hey @overlordnyaldee and everyone else on this thread this repository is being deprecated in favor of this one: 

https://github.com/zendesk/zendesk_sdk_ios

Additionally you can find detailed technical documentation here: 

https://developer.zendesk.com/embeddables/docs/ios/overview

And finally reference customers here:

https://www.zendesk.com/embeddables
