### ISSUE TITLE
Do you have examples of apps currently using this SDK?

### ISSUE THREAD

**Issue by rpparas** [zendesk/zendesk_ios_sdk#9]
Our app is still currently in the design phase but we'd like to see apps which are currently using this SDK so we can see the design and functionality.

**Comment by maximeprades** [comment]
Hey @rpparas this repository is being deprecated in favor of this one: 

https://github.com/zendesk/zendesk_sdk_ios

Additionally you can find detailed technical documentation here: 

https://developer.zendesk.com/embeddables/docs/ios/overview

And finally reference customers here:

https://www.zendesk.com/embeddables
